### ISSUE TITLE
Filter quickfix events (or integrate with dispatch)

### ISSUE THREAD

**Issue by SevereOverfl0w** [romainl/vim-qf#85] opened 2019-02-07 15:50 UTC
I opened [this issue](https://github.com/tpope/vim-dispatch/issues/256) at dispatch.vim which doesn't always populate the quickfix when it fires a QuickFixCmdPost.

The advice is to filter to only some events, or maybe filter out dispatch? Not sure. I just don't want to see an old quickfix buffer when I run certain commands.

**Comment by romainl** [comment] 2019-02-07 17:36
> It appears that vim-qf targets [literally every `QuickFixCmdPost` event](https://github.com/romainl/vim-qf/blob/master/plugin/qf.vim#L64-L65), which isn't compatible with our more nuanced uses. Instead, it should whitelist the particular commands it is actually targeting: `make,grep,grepadd,...`.

Vim-qf is generic by design. The idea is that `$PLUGIN_NAME`/`:command` only concerns itself with populating the quickfix/location list while vim-qf or some other similarly specialized plugin handles the quickfix/location list/window behavior. That design is incompatible with plugins that, IMO, overstep their boundaries like ALE or Syntastic. In this case, I feel like the Pope shouldn't use `:cgetfile` at all and instead rely on `setqflist()`. Or use only `:cgetfile`/`:cexpr` to avoid triggering `QuickFixCmdPost` events manually.

Or I could let my users optionally whitelist or blacklist commands. But I don't like that idea.

**Comment by romainl** [comment] 2021-03-28 14:17
I will close this issue because I don't plan to do anything about it.

**Closed by romainl** 2021-03-28 14:17 UTC
