### ISSUE TITLE
Conflicts with neomake

### ISSUE THREAD

**Issue by jpfender** [romainl/vim-qf#44] opened 2017-03-14 20:11 UTC
I don't know how much of this can be adressed on the vim-qf side, but there are some issues when vim-qf and neomake are used together.

If vim-qf is used out of the box without any configuration, the config option `let g:neomake_open_list` has no effect on the loclist opened by neomake regardless of what value it is set to. It appears that the behaviour of the loclist is overwritten by vim-qf.

If I set `let g:qf_auto_open_loclist = 0`, this does not prevent neomake from opening a loclist as you would expect, but it does allow neomake to bypass vim-qf for the loclist settings, meaning `neomake_open_list` settings now take effect.

However, some vim-qf settings and function calls, such as `qf_window_bottom` or `qf_loc_toggle_stay` still retain control over the neomake loclist.

So in effect, the communication between vim-qf and neomake does not work as one would intuitively expect; some, but not all of the settings do not transfer between the two.

**Comment by romainl** [comment] 2017-03-14 20:29
There's currently no attempt on either side to communicate with the other plugin. That would be a nightmare without a proper plugin API.

Anyway, I'll take a look at this issue ASAP.

**Comment by romainl** [comment] 2017-03-18 20:30
I've installed Neomake but now I'd like to see your settings for both Neomake and vim-qf in order to reproduce your context as faithfully as possible.

**Comment by jpfender** [comment] 2017-03-19 02:54
The following settings result in neomake opening the loclist on write, regardless of the fact that auto-opening the loclist is disabled in vim-qf. `auto_resize` also doesn't work, but `qf_loc_toggle_stay` does.

```
" neomake settings
autocmd! BufWritePost * Neomake
let g:neomake_open_list = 2

" vim-qf settings
nmap <F6> <Plug>(qf_loc_toggle_stay)
let g:qf_auto_open_loclist = 0
let g:qf_auto_resize = 1
```

Conversely, if you try the following settings:

```
" neomake settings
autocmd! BufWritePost * Neomake
let g:neomake_open_list = 0

" vim-qf settings
nmap <F6> <Plug>(qf_loc_toggle_stay)
let g:qf_auto_open_loclist = 1
let g:qf_auto_resize = 1
```

The loclist still gets opened on write, even though `neomake_open_list` is disabled. The loclist opened this way is fully controlled by vim-qf, meaning that `auto_resize` works, but the cursor will always automatically jump to the loclist, even if we set `neomake_open_list = 2`.

**Comment by romainl** [comment] 2017-03-19 16:44
It looks like both plugins have overlapping features, which makes sense because both plugins are heavily quickfix-oriented. I can see three directions to take:

1. Let the user try to make the two plugins work together by finding the right options combo.
2. Remove/disable the features in vim-qf that overlap with those in Neomake.
3. Remove/disable the features in Neomake that overlap with those in vim-qf.

I will certainly not take direction #2 and I doubt Neomake's author will take direction #3 so it looks like we are left with direction #1.

I think I will simply add a disclaimer in `README.md`.

Sorry, but this is a WONTFIX issue.

**Closed by romainl** 2017-03-19 16:44 UTC
Labels: bug, wontfix

**Comment by jpfender** [comment] 2017-03-19 20:02
Yes, that's fair enough. I had already taken direction 1 by myself, I mainly wanted to make sure I wasn't missing an obvious solution to the problem. Thank you for looking into this!

**Comment by blueyed** [comment] 2017-05-02 22:43
It seems like the annoying part with `g:qf_auto_open_loclist` is that it does not jump back to the previous window after all? (which vim-qf could add as a feature)
See https://github.com/neomake/neomake/issues/1097#issuecomment-298780826 for settings that work with Neomake.
